### ISSUE TITLE
Scrape subdivision 14 cases

### ISSUE THREAD

**Issue by fgregg** [datamade/court-scrapers#55]
The reporters would really like to get some older historical data for housing court cases (subdivision 14). Could we effectively just scrape these types of cases?

**Comment by fgregg** [comment]
as far back as possible

**Comment by antidipyramid** [comment]
And these are civil cases, right?

**Comment by fgregg** [comment]
if you set subdivision = 14 in the datasette filter, that is the cases we
want.
